=== daniel-makerx/typed-client-examples/algokit-client-generator-ts/src/schema/application.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "title": "AlgoAppSpec",
  "type": "object",
  "required": ["contract", "schema", "source", "state"],
  "additionalProperties": false,
  "properties": {
    "hints": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#/definitions/Hint"
      }
    },
    "source": {
      "$ref": "#/definitions/AppSources"
    },
    "contract": {
      "$ref": "contract.schema.json"
    },
    "schema": {
      "$ref": "#/definitions/SchemaSpec"
    },
    "state": {
      "$ref": "#/definitions/StateSchemaSpec"
    },
    "bare_call_config": {
      "$ref": "#/definitions/CallConfig"
    }
  },
  "definitions": {
    "AVMType": {
      "enum": ["uint64", "bytes"]
    },
    "DeclaredSchemaValueSpec": {
      "type": "object",
      "required": ["type", "key"],
      "additionalProperties": false,
      "properties": {
        "type": {
          "description": "The type of the value",
          "$ref": "#/definitions/AVMType"
        },
        "key": {
          "description": "The name of the key",
          "type": "string"
        },
        "descr": {
          "description": "A description of the variable",
          "type": "string"
        },
        "static": {
          "description": "Whether the value is set statically (at create time only) or dynamically",
          "type": "boolean"
        }
      }
    },
    "ReservedSchemaValueSpec": {
      "type": "object",
      "required": ["type"],
      "properties": {
        "type": {
          "description": "The type of the value",
          "$ref": "#/definitions/AVMType"
        },
        "descr": {
          "description": "A description of the variable",
          "type": "string"
        },
        "max_keys": {
          "description": "The maximum number of slots to reserve",
          "type": "integer"
        }
      }
    },
    "StateSchemaSpec": {
      "type": "object",
      "additionalProperties": false,
      "required": ["global", "local"],
      "properties": {
        "global": {
          "$ref": "#/definitions/StateSchema"
        },
        "local": {
          "$ref": "#/definitions/StateSchema"
        }
      }
    },
    "StateSchema": {
      "type": "object",
      "additionalProperties": false,
      "required": ["num_byte_slices", "num_uints"],
      "properties": {
        "num_uints": {
          "type": "integer"
        },
        "num_byte_slices": {
          "type": "integer"
        }
      }
    },
    "SchemaSpec": {
      "description": "The schema for global and local storage",
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "global": {
          "$ref": "#/definitions/Schema"
        },
        "local": {
          "$ref": "#/definitions/Schema"
        }
      }
    },
    "Schema": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "declared": {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/definitions/DeclaredSchemaValueSpec"
          }
        },
        "reserved": {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/definitions/ReservedSchemaValueSpec"
          }
        }
      }
    },
    "AppSources": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "approval": {
          "type": "string"
        },
        "clear": {
          "type": "string"
        }
      }
    },
    "Hint": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "read_only": {
          "type": "boolean"
        },
        "structs": {
          "type": "object",
          "properties": {
            "output": {
              "$ref": "#/definitions/Struct"
            }
          },
          "additionalProperties": {
            "$ref": "#/definitions/Struct"
          }
        },
        "default_arguments": {
          "additionalProperties": {
            "$ref": "#/definitions/DefaultArgument"
          }
        },
        "call_config": {
          "$ref": "#/definitions/CallConfig"
        }
      }
    },
    "CallConfig": {
      "type": "object",
      "minProperties": 1,
      "additionalProperties": false,
      "properties": {
        "no_op": {
          "$ref": "#/definitions/CallConfigValue"
        },
        "opt_in": {
          "$ref": "#/definitions/CallConfigValue"
        },
        "close_out": {
          "$ref": "#/definitions/CallConfigValue"
        },
        "update_application": {
          "$ref": "#/definitions/CallConfigValue"
        },
        "delete_application": {
          "$ref": "#/definitions/CallConfigValue"
        }
      }
    },
    "CallConfigValue": {
      "enum": ["NEVER", "CALL", "CREATE", "ALL"]
    },
    "Struct": {
      "type": "object",
      "additionalProperties": false,
      "required": ["name", "elements"],
      "properties": {
        "name": {
          "type": "string"
        },
        "elements": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/StructElement"
          }
        }
      }
    },
    "FieldName": {
      "type": "string"
    },
    "ABIType": {
      "type": "string"
    },
    "StructElement": {
      "type": "array",
      "minItems": 2,
      "items": [
        {
          "$ref": "#/definitions/FieldName"
        },
        {
          "$ref": "#/definitions/ABIType"
        }
      ]
    },
    "DefaultArgument": {
      "properties": {
        "source": {
          "$ref": "#/definitions/ArgumentSource"
        },
        "data": {
          "oneOf": [
            {
              "type": "string"
            },
            {
              "type": "number"
            },
            {
              "type": "integer"
            }
          ]
        }
      }
    },

    "ArgumentSource": {
      "enum": ["global-state", "local-state", "abi-method", "constant"]
    }
  }
}

=== daniel-makerx/typed-client-examples/smart_contracts/artifacts/LifeCycleApp/application.json
{
    "hints": {
        "hello(string)string": {
            "call_config": {
                "no_op": "CALL"
            }
        },
        "create_1arg(string)string": {
            "call_config": {
                "no_op": "CREATE"
            }
        },
        "create_2arg(string,uint32)void": {
            "call_config": {
                "no_op": "CREATE"
            }
        }
    },
    "source": {
        "approval": "I3ByYWdtYSB2ZXJzaW9uIDgKaW50Y2Jsb2NrIDAgMSAxMApieXRlY2Jsb2NrIDB4NzQ2OTZkNjU3MyAweCAweDY3NzI2NTY1NzQ2OTZlNjcgMHgxNTFmN2M3NQp0eG4gTnVtQXBwQXJncwppbnRjXzAgLy8gMAo9PQpibnogbWFpbl9sOAp0eG5hIEFwcGxpY2F0aW9uQXJncyAwCnB1c2hieXRlcyAweDAyYmVjZTExIC8vICJoZWxsbyhzdHJpbmcpc3RyaW5nIgo9PQpibnogbWFpbl9sNwp0eG5hIEFwcGxpY2F0aW9uQXJncyAwCnB1c2hieXRlcyAweGJjN2I2ZGY5IC8vICJjcmVhdGVfMWFyZyhzdHJpbmcpc3RyaW5nIgo9PQpibnogbWFpbl9sNgp0eG5hIEFwcGxpY2F0aW9uQXJncyAwCnB1c2hieXRlcyAweGQ4NjlmNjM2IC8vICJjcmVhdGVfMmFyZyhzdHJpbmcsdWludDMyKXZvaWQiCj09CmJueiBtYWluX2w1CmVycgptYWluX2w1Ogp0eG4gT25Db21wbGV0aW9uCmludGNfMCAvLyBOb09wCj09CnR4biBBcHBsaWNhdGlvbklECmludGNfMCAvLyAwCj09CiYmCmFzc2VydAp0eG5hIEFwcGxpY2F0aW9uQXJncyAxCnN0b3JlIDIKdHhuYSBBcHBsaWNhdGlvbkFyZ3MgMgppbnRjXzAgLy8gMApleHRyYWN0X3VpbnQzMgpzdG9yZSAzCmxvYWQgMgpsb2FkIDMKY2FsbHN1YiBjcmVhdGUyYXJnXzYKaW50Y18xIC8vIDEKcmV0dXJuCm1haW5fbDY6CnR4biBPbkNvbXBsZXRpb24KaW50Y18wIC8vIE5vT3AKPT0KdHhuIEFwcGxpY2F0aW9uSUQKaW50Y18wIC8vIDAKPT0KJiYKYXNzZXJ0CnR4bmEgQXBwbGljYXRpb25BcmdzIDEKY2FsbHN1YiBjcmVhdGUxYXJnXzUKc3RvcmUgMQpieXRlY18zIC8vIDB4MTUxZjdjNzUKbG9hZCAxCmNvbmNhdApsb2cKaW50Y18xIC8vIDEKcmV0dXJuCm1haW5fbDc6CnR4biBPbkNvbXBsZXRpb24KaW50Y18wIC8vIE5vT3AKPT0KdHhuIEFwcGxpY2F0aW9uSUQKaW50Y18wIC8vIDAKIT0KJiYKYXNzZXJ0CnR4bmEgQXBwbGljYXRpb25BcmdzIDEKY2FsbHN1YiBoZWxsb18zCnN0b3JlIDAKYnl0ZWNfMyAvLyAweDE1MWY3Yzc1CmxvYWQgMApjb25jYXQKbG9nCmludGNfMSAvLyAxCnJldHVybgptYWluX2w4Ogp0eG4gT25Db21wbGV0aW9uCmludGNfMCAvLyBOb09wCj09CmJueiBtYWluX2wxNAp0eG4gT25Db21wbGV0aW9uCmludGNfMSAvLyBPcHRJbgo9PQpibnogbWFpbl9sMTMKdHhuIE9uQ29tcGxldGlvbgpwdXNoaW50IDQgLy8gVXBkYXRlQXBwbGljYXRpb24KPT0KYm56IG1haW5fbDEyCmVycgptYWluX2wxMjoKdHhuIEFwcGxpY2F0aW9uSUQKaW50Y18wIC8vIDAKIT0KYXNzZXJ0CmNhbGxzdWIgdXBkYXRlXzIKaW50Y18xIC8vIDEKcmV0dXJuCm1haW5fbDEzOgp0eG4gQXBwbGljYXRpb25JRAppbnRjXzAgLy8gMAo9PQphc3NlcnQKY2FsbHN1YiBiYXJlY3JlYXRlXzQKaW50Y18xIC8vIDEKcmV0dXJuCm1haW5fbDE0Ogp0eG4gQXBwbGljYXRpb25JRAppbnRjXzAgLy8gMAo9PQphc3NlcnQKY2FsbHN1YiBiYXJlY3JlYXRlXzQKaW50Y18xIC8vIDEKcmV0dXJuCgovLyBpbnRfdG9fYXNjaWkKaW50dG9hc2NpaV8wOgpwcm90byAxIDEKcHVzaGJ5dGVzIDB4MzAzMTMyMzMzNDM1MzYzNzM4MzkgLy8gIjAxMjM0NTY3ODkiCmZyYW1lX2RpZyAtMQppbnRjXzEgLy8gMQpleHRyYWN0MwpyZXRzdWIKCi8vIGl0b2EKaXRvYV8xOgpwcm90byAxIDEKZnJhbWVfZGlnIC0xCmludGNfMCAvLyAwCj09CmJueiBpdG9hXzFfbDUKZnJhbWVfZGlnIC0xCmludGNfMiAvLyAxMAovCmludGNfMCAvLyAwCj4KYm56IGl0b2FfMV9sNApieXRlY18xIC8vICIiCml0b2FfMV9sMzoKZnJhbWVfZGlnIC0xCmludGNfMiAvLyAxMAolCmNhbGxzdWIgaW50dG9hc2NpaV8wCmNvbmNhdApiIGl0b2FfMV9sNgppdG9hXzFfbDQ6CmZyYW1lX2RpZyAtMQppbnRjXzIgLy8gMTAKLwpjYWxsc3ViIGl0b2FfMQpiIGl0b2FfMV9sMwppdG9hXzFfbDU6CnB1c2hieXRlcyAweDMwIC8vICIwIgppdG9hXzFfbDY6CnJldHN1YgoKLy8gdXBkYXRlCnVwZGF0ZV8yOgpwcm90byAwIDAKdHhuIFNlbmRlcgpnbG9iYWwgQ3JlYXRvckFkZHJlc3MKPT0KLy8gdW5hdXRob3JpemVkCmFzc2VydApwdXNoaW50IFRNUExfVVBEQVRBQkxFIC8vIFRNUExfVVBEQVRBQkxFCi8vIENoZWNrIGFwcCBpcyB1cGRhdGFibGUKYXNzZXJ0CnJldHN1YgoKLy8gaGVsbG8KaGVsbG9fMzoKcHJvdG8gMSAxCmJ5dGVjXzEgLy8gIiIKYnl0ZWNfMSAvLyAiIgpzdG9yZSA0CmludGNfMCAvLyAwCnN0b3JlIDUKaGVsbG9fM19sMToKbG9hZCA1CmJ5dGVjXzAgLy8gInRpbWVzIgphcHBfZ2xvYmFsX2dldAo8CmJ6IGhlbGxvXzNfbDMKbG9hZCA0CmJ5dGVjXzIgLy8gImdyZWV0aW5nIgphcHBfZ2xvYmFsX2dldApjb25jYXQKcHVzaGJ5dGVzIDB4MmMyMCAvLyAiLCAiCmNvbmNhdApmcmFtZV9kaWcgLTEKZXh0cmFjdCAyIDAKY29uY2F0CnB1c2hieXRlcyAweDBhIC8vICJcbiIKY29uY2F0CnN0b3JlIDQKbG9hZCA1CmludGNfMSAvLyAxCisKc3RvcmUgNQpiIGhlbGxvXzNfbDEKaGVsbG9fM19sMzoKbG9hZCA0CmZyYW1lX2J1cnkgMApmcmFtZV9kaWcgMApsZW4KaXRvYgpleHRyYWN0IDYgMApmcmFtZV9kaWcgMApjb25jYXQKZnJhbWVfYnVyeSAwCnJldHN1YgoKLy8gYmFyZV9jcmVhdGUKYmFyZWNyZWF0ZV80Ogpwcm90byAwIDAKYnl0ZWNfMiAvLyAiZ3JlZXRpbmciCnB1c2hieXRlcyAweDQ4NjU2YzZjNmYgLy8gIkhlbGxvIgphcHBfZ2xvYmFsX3B1dApieXRlY18wIC8vICJ0aW1lcyIKaW50Y18xIC8vIDEKYXBwX2dsb2JhbF9wdXQKaW50Y18xIC8vIDEKcmV0dXJuCgovLyBjcmVhdGVfMWFyZwpjcmVhdGUxYXJnXzU6CnByb3RvIDEgMQpieXRlY18xIC8vICIiCmJ5dGVjXzIgLy8gImdyZWV0aW5nIgpmcmFtZV9kaWcgLTEKZXh0cmFjdCAyIDAKYXBwX2dsb2JhbF9wdXQKYnl0ZWNfMCAvLyAidGltZXMiCmludGNfMSAvLyAxCmFwcF9nbG9iYWxfcHV0CmZyYW1lX2RpZyAtMQpleHRyYWN0IDIgMApwdXNoYnl0ZXMgMHg1ZiAvLyAiXyIKY29uY2F0CmJ5dGVjXzAgLy8gInRpbWVzIgphcHBfZ2xvYmFsX2dldApjYWxsc3ViIGl0b2FfMQpjb25jYXQKZnJhbWVfYnVyeSAwCmZyYW1lX2RpZyAwCmxlbgppdG9iCmV4dHJhY3QgNiAwCmZyYW1lX2RpZyAwCmNvbmNhdApmcmFtZV9idXJ5IDAKcmV0c3ViCgovLyBjcmVhdGVfMmFyZwpjcmVhdGUyYXJnXzY6CnByb3RvIDIgMApieXRlY18yIC8vICJncmVldGluZyIKZnJhbWVfZGlnIC0yCmV4dHJhY3QgMiAwCmFwcF9nbG9iYWxfcHV0CmJ5dGVjXzAgLy8gInRpbWVzIgpmcmFtZV9kaWcgLTEKYXBwX2dsb2JhbF9wdXQKaW50Y18xIC8vIDEKcmV0dXJu",
        "clear": "I3ByYWdtYSB2ZXJzaW9uIDgKaW50Y2Jsb2NrIDEKY2FsbHN1YiBjbGVhcl8wCmludGNfMCAvLyAxCnJldHVybgoKLy8gY2xlYXIKY2xlYXJfMDoKcHJvdG8gMCAwCmludGNfMCAvLyAxCnJldHVybg=="
    },
    "state": {
        "global": {
            "num_byte_slices": 1,
            "num_uints": 1
        },
        "local": {
            "num_byte_slices": 0,
            "num_uints": 0
        }
    },
    "schema": {
        "global": {
            "declared": {
                "greeting": {
                    "type": "bytes",
                    "key": "greeting",
                    "descr": ""
                },
                "times": {
                    "type": "uint64",
                    "key": "times",
                    "descr": ""
                }
            },
            "reserved": {}
        },
        "local": {
            "declared": {},
            "reserved": {}
        }
    },
    "contract": {
        "name": "LifeCycleApp",
        "methods": [
            {
                "name": "hello",
                "args": [
                    {
                        "type": "string",
                        "name": "name"
                    }
                ],
                "returns": {
                    "type": "string"
                }
            },
            {
                "name": "create_1arg",
                "args": [
                    {
                        "type": "string",
                        "name": "greeting"
                    }
                ],
                "returns": {
                    "type": "string"
                },
                "desc": "ABI create method with 1 argument"
            },
            {
                "name": "create_2arg",
                "args": [
                    {
                        "type": "string",
                        "name": "greeting"
                    },
                    {
                        "type": "uint32",
                        "name": "times"
                    }
                ],
                "returns": {
                    "type": "void"
                },
                "desc": "ABI create method with 2 arguments"
            }
        ],
        "networks": {}
    },
    "bare_call_config": {
        "no_op": "CREATE",
        "opt_in": "CREATE",
        "update_application": "CALL"
    }
}
